name: Simple Log Analysis Test

on:
  workflow_dispatch:
    inputs:
      access_code:
        description: 'Access Code'
        required: true
        type: string

jobs:
  validate-and-act:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Access Code
        env:
          ACCESS_CODE_HASH: ${{ secrets.ACCESS_CODE_HASH }}
        run: |
          # Calculate the SHA256 hash of the provided access code
          echo "${{ github.event.inputs.access_code }}" | sha256sum | awk '{print $1}' | tr '[:upper:]' '[:lower:]' > computed_hash.txt
          # Compare the calculated hash with the stored hash
          if ! cmp -s computed_hash.txt <(echo $ACCESS_CODE_HASH); then
            echo "Access code validation failed."
            exit 1
          fi

      - name: Create Issue with Sample Log Analysis
        if: success()  # Only proceed if the above step was successful
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const issueTitle = 'Kubernetes Pod Log Analysis Test';
            const issueBody = `### Kubernetes Pod Log Analysis

            Here's a snippet from the Kubernetes pod logs:

            \`\`\`
            2023-11-19T12:30:00.000Z [info]  Application starting...
            2023-11-19T12:30:15.000Z [info]  Database connection established.
            2023-11-19T12:32:00.000Z [warn]  Database query took longer than 500ms, potential performance bottleneck.
            2023-11-19T12:33:00.000Z [error] Failed to connect to external service: Connection refused
            2023-11-19T12:35:00.000Z [info]  External service now reachable, resuming normal operation.
            2023-11-19T12:40:00.000Z [info]  Processing batch job #12345.
            2023-11-19T12:45:00.000Z [warn]  Memory usage is at 85%, monitor for potential issues.
            2023-11-19T12:50:00.000Z [error] Out of memory error during batch job processing. Job #12345 was terminated.
            2023-11-19T12:55:00.000Z [info]  Application restarted after OutOfMemoryError, health checks passed.
            2023-11-19T13:00:00.000Z [info]  New request received at /api/v1/data endpoint.
            2023-11-19T13:05:00.000Z [warn]  Retrying operation after temporary network issue.
            \`\`\`

            **Analysis Results:**
            - **Warnings Detected:**
              - At 12:32:00Z, a performance bottleneck was noted with database queries.
              - Memory usage warning at 12:45:00Z indicating potential for OutOfMemory errors.
              - Network retry warning at 13:05:00Z due to temporary issues.

            - **Errors Found:**
              - Connection to external service failed at 12:33:00Z.
              - An OutOfMemoryError occurred at 12:50:00Z during job processing.

            - **Info Logs:**
              - Application startup and normal operations were logged.

            **Recommendations:**
            - Investigate the database query performance issue.
            - Review the application's memory usage and consider increasing resource limits or optimizing memory usage.
            - Check configurations for external service connections and implement retry logic with backoff.
            - Monitor network stability and consider implementing circuit breaker patterns for network-related operations.`;

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
            });
